backend:
  name: github
  repo: YOUR_GITHUB_USERNAME/YOUR_REPO_NAME
  branch: main

publish_mode: editorial_workflow

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

site_url: "https://moini.org"

collections:
  - name: "posts"
    label: "Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Subtitle", name: "subtitle", widget: "string", required: false }
      - { label: "Hero Image", name: "hero_image", widget: "image", required: false }
      - { label: "Hero Alt Text", name: "hero_alt", widget: "string", required: false }
      - { label: "Hero Caption", name: "hero_caption", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Pages"
    files:
      - label: "Resume"
        name: "resume"
        file: "resume/index.html"
        fields:
          - { label: "Layout", name: "layout", widget: "hidden", default: "default" }
          - { label: "Title", name: "title", widget: "hidden", default: "Resume" }
          - { label: "Body", name: "body", widget: "markdown" }
